#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BeautyBookCustomerApp.Droid.Resource", IsApplication=true)]

namespace BeautyBookCustomerApp.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.1.0.5")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int BeautyBook_logo = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int calender_icon = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int eye_icon = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int hide_eye_icon = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int location_icon = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int minus_icon = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int plus_icon = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int profile_cover = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int reena_salon = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int salon_logo = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int search_icon = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int time_icon = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int BeautyBook_logo = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int icon_round = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int launcher_foreground = 2130903043;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
